
import './globals.css'
import { Inter, Ubuntu } from 'next/font/google'
import Navbar from '@/component/Navbar/Navbar'
import Provider from '@/component/Provider/Provider'
import { ModalProvider } from '@/context/ModalContext'

const inter = Inter({ subsets: ['latin'] })
const ubuntu = Ubuntu({
  weight: ['300', '400', '500', '700' ],
   subsets: ['greek'] 
  })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
      <ModalProvider>
        <Provider>
        <Navbar />
          {children}
        </Provider>
      </ModalProvider>
      </body>
    </html>
  )
}
